on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

name: Continuous integration

jobs:
  check:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt

      - name: rustfmt check
        run: cargo fmt --all -- --check

      - name: cargo doc
        run: cargo doc --all-features --document-private-items --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

  clippy-lint:
    name: Clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo clippy --all-features
        run: cargo clippy --all-features --all-targets -- -D warnings

  test-stable:
    name: cargo test stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@stable

        # because --all-targets doesn't run doctests
      - name: cargo test
        run: cargo test

      - name: cargo test --all-targets --all-features
        run: cargo test  --all-targets --all-features
